//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `test.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let Test = _ModuleRegistry.module("Test");

    const iceC_Test_RangerAccessResource_ids = [
        "::Ice::Object",
        "::Test::RangerAccessResource"
    ];

    Test.RangerAccessResource = class extends Ice.Object
    {
    };

    Test.RangerAccessResourcePrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Test.RangerAccessResource, Test.RangerAccessResourcePrx, iceC_Test_RangerAccessResource_ids, 1);

    const iceC_Test_RangerAccessResourceImp_ids = [
        "::Ice::Object",
        "::Test::RangerAccessResource",
        "::Test::RangerAccessResourceImp"
    ];

    Test.RangerAccessResourceImp = class extends Ice.Value
    {
        constructor(ownerUser = "")
        {
            super();
            this.ownerUser = ownerUser;
        }

        _iceWriteMemberImpl(ostr)
        {
            ostr.writeString(this.ownerUser);
        }

        _iceReadMemberImpl(istr)
        {
            this.ownerUser = istr.readString();
        }
    };

    Slice.defineValue(Test.RangerAccessResourceImp, iceC_Test_RangerAccessResourceImp_ids[2], false);

    const iceC_Test_RangerAccessRequest_ids = [
        "::Ice::Object",
        "::Test::RangerAccessRequest"
    ];

    Test.RangerAccessRequest = class extends Ice.Object
    {
    };

    Test.RangerAccessRequestPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Test.RangerAccessRequest, Test.RangerAccessRequestPrx, iceC_Test_RangerAccessRequest_ids, 1,
    {
        "getResource": [, , , , ["Ice.Value", true], , , , , true]
    });
    exports.Test = Test;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
